name: ip_semear_sermoes
description: An application to listen to the IP Semear podcasts
publish_to: 'none'
version: 1.1.2+4

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  audio_service: ^0.18.9
  auto_scroll_text: ^0.0.6
  background_mode_new: ^1.0.3
  dio: ^4.0.6
  drift: ^2.4.2
  expandable: ^5.0.1
  get_it: ^7.2.0
  just_audio:
    path: ../just_audio/just_audio
  liquid_pull_to_refresh: ^3.0.1
  html: ^0.15.1
  path: ^1.8.3
  path_provider: ^2.0.11
  permission_handler: ^10.2.0
  sqlite3_flutter_libs: ^0.5.12

dev_dependencies:
  flutter_lints: ^2.0.1
  drift_dev: ^2.4.1
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/