name: ip_semear_sermoes
description: An application to listen to the IP Semear podcasts
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^1.1.1
  audio_service: ^0.18.7
  dio: ^4.0.6
  expandable: ^5.0.1
  html: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/