name: ip_semear_sermoes
description: An application to listen to the IP Semear podcasts
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  audio_service: ^0.18.7
  audio_video_progress_bar: ^0.11.0
  dio: ^4.0.6
  expandable: ^5.0.1
  just_audio: ^0.9.30
  html: ^0.15.1
  path_provider: ^2.0.11
  rxdart: ^0.27.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/